// Generated by gencpp from file decision_make/diagnose_msg.msg
// DO NOT EDIT!


#ifndef DECISION_MAKE_MESSAGE_DIAGNOSE_MSG_H
#define DECISION_MAKE_MESSAGE_DIAGNOSE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace decision_make
{
template <class ContainerAllocator>
struct diagnose_msg_
{
  typedef diagnose_msg_<ContainerAllocator> Type;

  diagnose_msg_()
    : current_1(0.0)
    , current_2(0.0)
    , current_3(0.0)
    , current_4(0.0)
    , battery(0.0)  {
    }
  diagnose_msg_(const ContainerAllocator& _alloc)
    : current_1(0.0)
    , current_2(0.0)
    , current_3(0.0)
    , current_4(0.0)
    , battery(0.0)  {
  (void)_alloc;
    }



   typedef float _current_1_type;
  _current_1_type current_1;

   typedef float _current_2_type;
  _current_2_type current_2;

   typedef float _current_3_type;
  _current_3_type current_3;

   typedef float _current_4_type;
  _current_4_type current_4;

   typedef float _battery_type;
  _battery_type battery;




  typedef boost::shared_ptr< ::decision_make::diagnose_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision_make::diagnose_msg_<ContainerAllocator> const> ConstPtr;

}; // struct diagnose_msg_

typedef ::decision_make::diagnose_msg_<std::allocator<void> > diagnose_msg;

typedef boost::shared_ptr< ::decision_make::diagnose_msg > diagnose_msgPtr;
typedef boost::shared_ptr< ::decision_make::diagnose_msg const> diagnose_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision_make::diagnose_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision_make::diagnose_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision_make

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'decision_make': ['/home/magnam/catkin_ws/src/decision_make/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision_make::diagnose_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision_make::diagnose_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_make::diagnose_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_make::diagnose_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_make::diagnose_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_make::diagnose_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision_make::diagnose_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4677b8ef50602202d6d4f5957669124";
  }

  static const char* value(const ::decision_make::diagnose_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4677b8ef5060220ULL;
  static const uint64_t static_value2 = 0x2d6d4f5957669124ULL;
};

template<class ContainerAllocator>
struct DataType< ::decision_make::diagnose_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision_make/diagnose_msg";
  }

  static const char* value(const ::decision_make::diagnose_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision_make::diagnose_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 current_1\n\
float32 current_2\n\
float32 current_3\n\
float32 current_4\n\
float32 battery\n\
";
  }

  static const char* value(const ::decision_make::diagnose_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision_make::diagnose_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_1);
      stream.next(m.current_2);
      stream.next(m.current_3);
      stream.next(m.current_4);
      stream.next(m.battery);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct diagnose_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision_make::diagnose_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision_make::diagnose_msg_<ContainerAllocator>& v)
  {
    s << indent << "current_1: ";
    Printer<float>::stream(s, indent + "  ", v.current_1);
    s << indent << "current_2: ";
    Printer<float>::stream(s, indent + "  ", v.current_2);
    s << indent << "current_3: ";
    Printer<float>::stream(s, indent + "  ", v.current_3);
    s << indent << "current_4: ";
    Printer<float>::stream(s, indent + "  ", v.current_4);
    s << indent << "battery: ";
    Printer<float>::stream(s, indent + "  ", v.battery);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MAKE_MESSAGE_DIAGNOSE_MSG_H
