// Generated by gencpp from file decision_make/rpm_msg.msg
// DO NOT EDIT!


#ifndef DECISION_MAKE_MESSAGE_RPM_MSG_H
#define DECISION_MAKE_MESSAGE_RPM_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace decision_make
{
template <class ContainerAllocator>
struct rpm_msg_
{
  typedef rpm_msg_<ContainerAllocator> Type;

  rpm_msg_()
    : motor_1(0.0)
    , motor_2(0.0)
    , motor_3(0.0)
    , motor_4(0.0)  {
    }
  rpm_msg_(const ContainerAllocator& _alloc)
    : motor_1(0.0)
    , motor_2(0.0)
    , motor_3(0.0)
    , motor_4(0.0)  {
  (void)_alloc;
    }



   typedef float _motor_1_type;
  _motor_1_type motor_1;

   typedef float _motor_2_type;
  _motor_2_type motor_2;

   typedef float _motor_3_type;
  _motor_3_type motor_3;

   typedef float _motor_4_type;
  _motor_4_type motor_4;




  typedef boost::shared_ptr< ::decision_make::rpm_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision_make::rpm_msg_<ContainerAllocator> const> ConstPtr;

}; // struct rpm_msg_

typedef ::decision_make::rpm_msg_<std::allocator<void> > rpm_msg;

typedef boost::shared_ptr< ::decision_make::rpm_msg > rpm_msgPtr;
typedef boost::shared_ptr< ::decision_make::rpm_msg const> rpm_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision_make::rpm_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision_make::rpm_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision_make

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'decision_make': ['/home/magnam/catkin_ws/src/decision_make/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision_make::rpm_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision_make::rpm_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_make::rpm_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_make::rpm_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_make::rpm_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_make::rpm_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision_make::rpm_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af4e003e6dd1d8c2d5dfe1f94487a00d";
  }

  static const char* value(const ::decision_make::rpm_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf4e003e6dd1d8c2ULL;
  static const uint64_t static_value2 = 0xd5dfe1f94487a00dULL;
};

template<class ContainerAllocator>
struct DataType< ::decision_make::rpm_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision_make/rpm_msg";
  }

  static const char* value(const ::decision_make::rpm_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision_make::rpm_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 motor_1\n\
float32 motor_2\n\
float32 motor_3\n\
float32 motor_4\n\
";
  }

  static const char* value(const ::decision_make::rpm_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision_make::rpm_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_1);
      stream.next(m.motor_2);
      stream.next(m.motor_3);
      stream.next(m.motor_4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rpm_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision_make::rpm_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision_make::rpm_msg_<ContainerAllocator>& v)
  {
    s << indent << "motor_1: ";
    Printer<float>::stream(s, indent + "  ", v.motor_1);
    s << indent << "motor_2: ";
    Printer<float>::stream(s, indent + "  ", v.motor_2);
    s << indent << "motor_3: ";
    Printer<float>::stream(s, indent + "  ", v.motor_3);
    s << indent << "motor_4: ";
    Printer<float>::stream(s, indent + "  ", v.motor_4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MAKE_MESSAGE_RPM_MSG_H
