// Generated by gencpp from file decision_make/ultrasonic_msg.msg
// DO NOT EDIT!


#ifndef DECISION_MAKE_MESSAGE_ULTRASONIC_MSG_H
#define DECISION_MAKE_MESSAGE_ULTRASONIC_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace decision_make
{
template <class ContainerAllocator>
struct ultrasonic_msg_
{
  typedef ultrasonic_msg_<ContainerAllocator> Type;

  ultrasonic_msg_()
    : ultrasonic(0.0)  {
    }
  ultrasonic_msg_(const ContainerAllocator& _alloc)
    : ultrasonic(0.0)  {
  (void)_alloc;
    }



   typedef float _ultrasonic_type;
  _ultrasonic_type ultrasonic;




  typedef boost::shared_ptr< ::decision_make::ultrasonic_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decision_make::ultrasonic_msg_<ContainerAllocator> const> ConstPtr;

}; // struct ultrasonic_msg_

typedef ::decision_make::ultrasonic_msg_<std::allocator<void> > ultrasonic_msg;

typedef boost::shared_ptr< ::decision_make::ultrasonic_msg > ultrasonic_msgPtr;
typedef boost::shared_ptr< ::decision_make::ultrasonic_msg const> ultrasonic_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decision_make::ultrasonic_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decision_make::ultrasonic_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decision_make

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'decision_make': ['/home/magnam/catkin_ws/src/decision_make/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decision_make::ultrasonic_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decision_make::ultrasonic_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_make::ultrasonic_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decision_make::ultrasonic_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_make::ultrasonic_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decision_make::ultrasonic_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decision_make::ultrasonic_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e437e5b52cf30316ee33a4be62d1866";
  }

  static const char* value(const ::decision_make::ultrasonic_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e437e5b52cf3031ULL;
  static const uint64_t static_value2 = 0x6ee33a4be62d1866ULL;
};

template<class ContainerAllocator>
struct DataType< ::decision_make::ultrasonic_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decision_make/ultrasonic_msg";
  }

  static const char* value(const ::decision_make::ultrasonic_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decision_make::ultrasonic_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 ultrasonic\n\
";
  }

  static const char* value(const ::decision_make::ultrasonic_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decision_make::ultrasonic_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ultrasonic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultrasonic_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decision_make::ultrasonic_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decision_make::ultrasonic_msg_<ContainerAllocator>& v)
  {
    s << indent << "ultrasonic: ";
    Printer<float>::stream(s, indent + "  ", v.ultrasonic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECISION_MAKE_MESSAGE_ULTRASONIC_MSG_H
